### ISSUE TITLE
Wall pictures lost after sharing or high number of pins in a pinwall

### ISSUE THREAD

**Issue by ernesst** [libasys/ownCloud-8.1-Pinit-App#1]
Hi Libasys,

I would like to thank you for this great and useful owncloud app. 
I'm encountering a similar bug from two different origins. 

After adding more than 60 pins in a pinwall, it appear empty. However I can still access to them via the map. When I'm clicking back on maps button I'm get back an empty wall. 

The other case,
After sharing the pinwall with an internal owncloud user (I gave him full access), the pinwall appears empty. However the map is still working and displays all the pins, the other user gets also a pinwall empty but he can add pins which will appear on the map. 

When I start to get an empty wall, my other wall appear empty too. 

I'm willing to share more information on my server and your app utilisation however i don't know how to generate logfile with your app. 
Some information 
- Owncloud 8.1 beta 2
- Pinit app from a week ago
- + your app version : calendar, gallery, task
- PHP 5.5.26-1+deb.sury.org~trusty+1 (cli) (built: Jun 15 2015 10:13:03) 
- mysql  Ver 14.14 Distrib 5.5.43, for debian-linux-gnu (x86_64) using readline 6.3

Let me know if i can provide more information.

Regards
Ernesst

**Comment by libasys** [comment]
Thanks for the bug report, i have a deeper look into this issue! Which browser do you use? You can find the log on the admin settings  leftside bar "Logs"!

**Comment by libasys** [comment]
New version is available, please test! Thanks!

**Comment by ernesst** [comment]
In the admin settings, i don't find any error, fatal or warning related to Pin it, only fatal from calendar :). 
Usually I'm using ubuntu + firefox or chromium. 

I tried at work today with a WIn 7 + firefox, i get interesting results. 
I'm able to generate the same issue as describe above however i found the trick to display all my pins. By going as much as I can down on the pinwall and going up again the message "all pin loaded" appears and the pin are loaded.

It looks like by going down into the pinwall, i'm forcing the loading of the page/script, isn't it ? 
Currently on my server the auction of loading seems not be anymore trigged by opening some of my pinwalls.

Great for the update I will install it tonight thanks

**Comment by ernesst** [comment]
Hi, 

I have now the version Pinit 1.0.1, i'm confirming you the presence of the bug.
At home under ubuntu, I tested the same trick to scroll down to "force" a reload/load and display all the pin without issue.

Regards

**Comment by libasys** [comment]
You have cleared your Browser Cache? The Bug should be fixed!

**Comment by ernesst** [comment]
Sorry I didn't do it. 
I don't have anymore the issue, thanks for your quick efficient feedback.
